spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://112.124.32.84:3306/oj_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 654160
  application:
    name:
#  config:
#    activate:
#      on-profile:
#        - prod

  #生产环境禁用接口文档
#  autoconfigure:
#    exclude: org.springdoc.core.configuration.SpringDocConfiguration

server:
  port: 8080
  servlet:
    context-path: /api
#    session:
#      cookie:
#        same-site: none
#        secure: true

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:mapper/*Mapper.xml

#自定义代码沙箱类型
codesandbox:
  #  共三种 ExampleSandBox  remoteSandBox ThirdPartySandBoxImpl
  type: remoteSandBox
  url: http://112.124.32.84:8088/sandbox/execute

#生产环境禁用接口文档
#springdoc:
#  api-docs:
#    enabled: false